### ISSUE TITLE
Launch screen does not resize properly on smaller devices

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_android#109]
After the initial download is finished, the tracking request is partially hidden behind the soft-buttons.

**Device model:** Galaxy Nexus
**Android version:** 6.0.1 (CyanogenMod 13.0-20161221-SNAPSHOT-ZNH5YAO3Y2-maguro)

![2017-07-12 17 23 36](https://user-images.githubusercontent.com/3359222/28125467-f8e25f6c-6726-11e7-9450-9fe60aa007d6.jpg)

**Comment by Requinard** [comment]
02732ac7ceb8be8fd7c81453b04df9e212b6d4f6
