### ISSUE TITLE
FCM Routing & Device Registration

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#110]
In order to be able to handle different notification payloads for Android and iOS, please implement the following changes:

1. (Un)Subscribing to topics on **FCM**:

- **Always**  subscribe to the topics `live-all` and `live-android`
- For **debug/testing** builds (anything that does not resemble the version that non-testers will get from the store), **additionally** subscribe to the topics `test-all` and `test-android`

2. POSTing the **FcmDeviceRegistration** upsert against the back-end:

- **Always** include the topic `live` and `android`
- For **debug/testing** builds (anything that does not resemble the version that non-testers will get from the store), **additionally** include the topic `test`
- Feel free to still include the `version-x.x.x.x` tag, and/or any other that may be relevant for your statistics.
- Send the POST request on **every status change of 'login'**, and additionally, on **every start of the application** (later one allows both for cleanup, and for getting actitivity statistics).

Those changes will allow the back-end to reliably route different payloads to Android and iOS consumers, both for broadcasts and individual notifications, and further allows test builds to still consume live notifications and thus be viable for usage during the convention.

**Comment by Requinard** [comment]
I'm looking at diffing through this

https://stackoverflow.com/questions/38212123/unsubscribe-from-all-topics-at-once-from-firebase-messaging
