### ISSUE TITLE
Favoriting an event scrolls down the page

### ISSUE THREAD

**Issue by Shad0X** [eurofurence/ef-app_android#113]
Every time I click on the Heart Icon and choose "Favorite Event" the page scrolls down a bit so that the heart icon is basically at the top of the page. 

Not really an issue, but still strange. 

App version - 2.0.6, build 71

**Comment by Requinard** [comment]
whenever you favourite an event, the entire UI is re-rendered. This is probably causing the jumping.

Will look for a fix

**Comment by lukashaertel** [comment]
Looking into it, but the behavior is really wierd.
