### ISSUE TITLE
App doesn't follow screen rotation; app may appear upside down

### ISSUE THREAD

**Issue by sschwarzer** [eurofurence/ef-app_android#115]
First off, this issue is _not_ about offering a landscape mode.

When I open the app on my tablet in _portrait_ orientation, with the back, home and menu button on the right, the app appears upside down. I can work around this by disabling automatic screen orientation, but of course this affects other apps with which I'd like to use automatic screen orientation. The other workaround is to hold the tablet "upside down" (with back, home and menu buttons on the left), but I find this inconvenient because I'm right-handed and strongly prefer to use these buttons with my right hand.

You don't need a tablet to reproduce this. I can also reproduce the issue by holding my smartphone upside-down and starting the app. It doesn't follow the screen orientation, but appears as if the smartphone wasn't held upside down. This probably isn't a practical use case, but I guess if you can reproduce and fix the issue on your device(s), it will also be fixed on my tablet. :-)

I'm not sure if this description is easy enough to understand. If necessary, I can try to give a more detailed explanation.

**Comment by sschwarzer** [comment]
I guess the problem is easier to see for yourself than to understand from my description.

Just turn your phone upside-down and start the app. In my opionion it should follow the upside-down rotation, but doesn't.

**Comment by Requinard** [comment]
App rotation has been disabled due to significant instability it incurs. Once the bugs have been worked out we'll enable them again but it's not working correctly for the time being
