### ISSUE TITLE
FcmDeviceRegistration Upsert not sent when logging out

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#116]
2.0.6, Build 71 - Verified on a Samsung Galaxy S7.

After logging out, there is no upsert against `FcmDeviceRegistration` - this causes the back-end to believe the user is still logged in, and will still send PMs to that device.

**Comment by Requinard** [comment]
Rodger dodger. Implementing this through a Logout event which will perform relevant actions
