### ISSUE TITLE
Show private message count on main screen

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#118]
When the user receives a private message, upon opening the application (after tapping the notification), they need to figure out where to find the view to read private messages.

Ideally, when private messages are present, show a button/indicator on the main view that directs them directly to the private message fragment.

**Comment by Requinard** [comment]
AFAIK I'm not supposed to be storing these messages. Maybe it's better if there's an API call for this? That way we can simply query the api to see if there's new messages and go from there.

**Comment by Pinselohrkater** [comment]
That's totally fine. WP does actually do just this: When the user is logged on, upon application start, I query the /PrivateMessages endpoint, and show them on the home screen.
