### ISSUE TITLE
Update Google Play store listing

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#122]
Update the Google Play store listing - I'm not exactly sure what is still '2016-ish'.

- Header / Banner 
- Screenshots

If you need any material/assets, please let me know, I should be able to provide them.

![photo_2017-07-30_16-33-39](https://user-images.githubusercontent.com/13329381/28754404-dd3dd15c-7544-11e7-9715-87cc9da1ff7a.jpg)

**Comment by Requinard** [comment]
Get me a banner for the appstore, screenshots will be generates soon(tm)

**Comment by Requinard** [comment]
status update?

**Comment by Requinard** [comment]
was updated earlier
