### ISSUE TITLE
Dealer Detail page does not show dealer location on map

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#123]
2.0.6, Build 71 - Verified on a Samsung Galaxy S7.

On the dealer detail page, the dealers den map is scrolled to the far right, not zoomed/centered on the dealer that was selected. (Tested with several, e.G. Apfelwolf, who is on the far left of the map).

**Comment by Requinard** [comment]
I really cannot get this to work. I'll probably remove the part if I can't fix it.

status:  The app finds the coordinates. The map is then scaled with a focalX and focalY. The focussing does not seem to work. Since this is a 3rd party library it's very unfortunate

**Comment by Pinselohrkater** [comment]
I think nobody will notice if that's missing. It's a minor detail, don't worry too much about it.
