### ISSUE TITLE
WikiText (Con Info) Line Breaks

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#128]
It seems the latest version (2.0.7) does not handle 'single line breaks' `\\` (two backslashes) very well.

Until we can provide markdown next year, please, please, please... take a look at the [wiki](https://wiki.eurofurence.org/doku.php?id=ef23:it:mobileapp:coninfo) and apply whatever magic/string manipulation you need to get somehow 'okay-ish' results.

(I know it sucks. But there's no way we can change the importer that close to convention.)

![image](https://user-images.githubusercontent.com/13329381/28978342-e137dcc6-7945-11e7-8a0d-606503e5c863.png)

**Comment by Requinard** [comment]
Did we not switch to markdown this year?
