### ISSUE TITLE
Linebreaks for long Event Titles

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#131]
2.0.8 - Long Event Titles do not line-break, and can be confusing to distinguish from one another.
 
![image](https://user-images.githubusercontent.com/13329381/29169585-05757df8-7dd5-11e7-9403-eace04dc893e.png)

**Comment by Requinard** [comment]
re-assigning to pazuzu because he did some funky stuff with this

**Comment by lukashaertel** [comment]
![photo_2018-07-26_17-47-29](https://user-images.githubusercontent.com/5929561/43273145-001fb0d6-90fc-11e8-9b74-d3884a116fe8.jpg)
Some frustrating line breaks (for event locations at least), but it works, sending to branch and creating a pr.
