### ISSUE TITLE
Event search results appear in random order

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_android#132]
When entering search mode on the event lists, results will no longer be ordered ascending by StartDateTimeUtc or follow any other apparent sorting as can be seen in attached screenshot.

![2017-08-10 15 20 01](https://user-images.githubusercontent.com/3359222/29172168-646d7ba8-7ddf-11e7-841a-cb8ad671e388.jpg)

**Comment by Requinard** [comment]
sorting search in alphabetical order
