### ISSUE TITLE
"Day 17391" at the top of the menu bar

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#133]
When remote config fails to load, the menu bar shows quite weird/high "Day" numbers (e.G. "Day 17391")

Can we provide some sane fallback values for those? Or hide it if the thing fails to initialize?

**Comment by Requinard** [comment]
Can't really find a fix right now for this.

**Comment by Requinard** [comment]
Thing is that there's default values in `remote.xml` that it should put if a fetch fails. It just doesn't seem to want to

**Comment by Requinard** [comment]
solved with 79afe82cbe3a13281bb639593bad73997a887d86
