### ISSUE TITLE
favorited events missing

### ISSUE THREAD

**Issue by friemt** [eurofurence/ef-app_android#141]
favorited events are not loaded/shown on the home screen on application startup. when selecting "Home" in the menu they show up.

**Comment by Requinard** [comment]
It's a known issue, however we've got no clue why this is happening

**Comment by friemt** [comment]
seems to also happen when app is loaded and i'm switching to the app via android notification

**Comment by mowny** [comment]
Which version? 2.0.12 seems to open the running instance (in the screen where I left it), while 2.0.10 opened a new one and thus got the problem described in op

**Comment by friemt** [comment]
just checked: it's 2.0.12

**Comment by Requinard** [comment]
b0d3d12f2ebb0b58478396d8d7afb1808d76a697

That should fix it
