### ISSUE TITLE
announcement notifications don't close 

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#143]
if there are attachments least 2 Android Notifications about announcements, 
opening them doesn't close the notification. 
probably something wrong in how notification id's are handled.

**Comment by Requinard** [comment]
17d6423c75318a1bb8620c28ebd55f61546cfb32

**Comment by MarcusWolschon** [comment]
No, setAutoCancel(true) does **not** fix this.
That only closes notification when you CLICK that specific notification.
That's why this bug mentions "at least 2 notification".

You want to remember the ID of your notifications and also close them when the user 
visit the page in the app that the notification is about even if the user has navigated there
manually.
