### ISSUE TITLE
Support Chat doesn't exist 

### ISSUE THREAD

**Issue by thygrrr** [eurofurence/ef-app_android#145]
When clicking on "Get help in the support Telegram", Telegram says "Sorry, this chat doesn't seem to exist"

**Comment by thygrrr** [comment]
Affects Android app.

**Comment by lukashaertel** [comment]
@thygrrr I can not reproduce this behavior. Can you validate if it's fixed or not?

**Comment by lukashaertel** [comment]
I can't reproduce the bug. It seems that the URL at that point in time did point to a group chat that does not exist. The new chat, as configured in the remote preferences does exist. Closing this bug for now.
