### ISSUE TITLE
Repeat Notifications 

### ISSUE THREAD

**Issue by thygrrr** [eurofurence/ef-app_android#146]
I get repeat announcements (e.g. about the non smoking rules), when I click on them, the app opens but doesn't display the announcement. 

Moreso, the in app announcement list doesn't mention the newest announcement yet. 

The new announcement periodically reoccurs, so far three times and counting...

**Comment by thygrrr** [comment]
Seven repeats and counting.

**Comment by thygrrr** [comment]
Workaround is to kill the app process. Then the notifications show up in the list and don't get repeated.

**Comment by Requinard** [comment]
this is to do with the rendering. I'll make a task a bout this

**Comment by Requinard** [comment]
b0d3d12f2ebb0b58478396d8d7afb1808d76a697

Fixed
