### ISSUE TITLE
sorting of favorited events list

### ISSUE THREAD

**Issue by friemt** [eurofurence/ef-app_android#147]
the favorited events list on the home page has some strange sorting. i get the list per day ascending but the items per day descending. for today the first two events starts at 6pm (18:00 localized) while the third starts at 10am (10:00 localized). problem with the time format? furthermore you may want to remove "done" events from the list (or at least from the top of the list)

**Comment by mowny** [comment]
Nope, it's not even descending, favorites intra-day order seems completely random. It worked in the versions before.
running 2.0.12 atm, and don't see an update in playstore.

**Comment by lukashaertel** [comment]
Addressed in #183

**Comment by lukashaertel** [comment]
Fix is merged
