### ISSUE TITLE
feature request: share button 

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#148]
Events should have a "share" action bar - action to inform others in a conversation about an event.

**Comment by Requinard** [comment]
As with all android items, a long press will bring up a context menu. Try long-pressing an event listing or the heart button on an event page.

It shares a link to the EF web app, which android can natively open

**Comment by MarcusWolschon** [comment]
That's not how apps that have an action bar shall present actions that refer to the entire activity.
This behavior is reserved for context-actions for single elements like selected text.
As such it is not intuitive even for lang standing Android users/developers without a graphical hint given.

https://developer.android.com/training/sharing/shareaction.html
https://developer.android.com/design/patterns/actionbar.html
