### ISSUE TITLE
New API Endpoint for non-prod branches

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#153]
For any "test/debug" builds (local developer versions, stuff that beta testers' on Google Play Store get) - please use:

https://app.eurofurence.org:40000/api/v2/

For prod/live builds, use:

https://app.eurofurence.org/api/v2/

**Comment by Requinard** [comment]
Storing this as a remote variable in Firebase

**Comment by Requinard** [comment]
done with release v2.1.0
