### ISSUE TITLE
UI Update: Knowledge Base List (General Convention Information)

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#157]
Update KB Listing according to Figma Mockup:
https://www.figma.com/file/0lVPXyRQyQoTzElnpCLjq31r/Knowledge-Base

- [x] Page Header: "Convention Information"
- [ ] List display, each item having:
  - [ ] FontAwesome icon (on left)
  - [x] Name & Description
  - [x] Dropdown chevron on the right; pointing down when not expanded, pointing up when expanded. (FontAwesome)
  - [x] A sub-list (grey background) listing the KB Entries for this group, visible when expanded, each item having:
    - [x] Title
    - [x] Chevron pointing to the right
    - [x] When tapped, open corresponding detail fragment
  - [x] FA Icon (left) & Group Chevron (right) are centered vertically
  - [x] Individual items expand vertically when Name or Descriptions line-wrap.

**Comment by lukashaertel** [comment]
Susbsumes #98

**Comment by lukashaertel** [comment]
FontAwesome should not have a problem with it, but using a unicode character directly seems not to display anything
