### ISSUE TITLE
Upon first start, load image assets synchronously (or wait for them).

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#160]
When the app is launched for the first time, images are loaded in background while the user is already on the home screen.

Navigating to "maps" or "dealers" while the async loading is still going on crashes the app.

-> Please load the images synchronously, aka. make the UI wait properly.

**Comment by lukashaertel** [comment]
Loading is asynchronous, refactoring preload to return an awaitable promise.

**Comment by lukashaertel** [comment]
Addressed in #187
