### ISSUE TITLE
Images that are scaled up cause photoView to have weird borders

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#172]
![image](https://user-images.githubusercontent.com/13329381/43327356-7d0702e2-91bb-11e8-9072-ea54d599385b.png)

**Comment by Pinselohrkater** [comment]
I got some positive results with

adjustViewBounds = true

on PhotoView & ImageView, but I'm not sure where to place those properly.

If possible, please apply this auto-sizing on:
- Knowledge Base Entry Detail
- Event Detail
- Dealer Detail

**Comment by lukashaertel** [comment]
Addressed in #175
