### ISSUE TITLE
Fragments sometimes get a null context

### ISSUE THREAD

**Issue by lukashaertel** [eurofurence/ef-app_android#190]
In some cases, i.e. after a having the app suspended for longer times, opening the app again causes the app to crash with a null pointer exception in fragment create view.
A possible solution might be in [this thread](https://stackoverflow.com/questions/47987649/why-getcontext-in-fragment-sometimes-returns-null).

**Comment by Pinselohrkater** [comment]
Was presumably fixed in #195 - I was unable to reproduce it.
