### ISSUE TITLE
Event details still pop

### ISSUE THREAD

**Issue by lukashaertel** [eurofurence/ef-app_android#203]
After rotating twice, event details pop. Not clearing the back stack on app restore fixes it. I don't like the back stack at all :(

**Comment by lukashaertel** [comment]
This [article](https://bricolsoftconsulting.com/state-preservation-in-backstack-fragments/) seems to be pointing to the right direction.

**Comment by lukashaertel** [comment]
Also [this](https://stackoverflow.com/a/26225201)

**Comment by Pinselohrkater** [comment]
Haven't been able to break backstack with any kind of rotation anymore.
