### ISSUE TITLE
Title of fragments on home screen do not align anymore

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#207]
Please ensure that the fragment titles (Upcoming Events, Favorited Events, Running Events...) are aligned with the "Announcements" fragment title.

Current state:

![screenshot_1533043965](https://user-images.githubusercontent.com/13329381/43462766-47f36860-94d7-11e8-9deb-218a327207d8.png)
![screenshot_1533043962](https://user-images.githubusercontent.com/13329381/43462768-484e513a-94d7-11e8-9704-6c99cc40900c.png)

Alignment guide:

![alscreenshot_1533043965](https://user-images.githubusercontent.com/13329381/43462823-6a479d28-94d7-11e8-81e6-e6b06036be43.png)

**Comment by lukashaertel** [comment]
Sorry about that, addressed now.
