### ISSUE TITLE
App crashes on force close and reopen

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_android#21]
App crashes and will need local file clearing to fix

* Open app
* Close app
* Go to app switcher
* Remove con Navigator app
* restart app
* App crashes

pls fix. issue is in the database

**Comment by lukashaertel** [comment]
Quickfix go to apps, clean cache for Eurofurence, database consistency is not checked, so there is probably a crash while writing making it inconsistent.

**Comment by Requinard** [comment]
This is not a fix though. Please fix it in code

On Thu, Apr 21, 2016, 3:12 PM Lukas Härtel <notifications@github.com> wrote:

> Quickfix go to apps, clean cache for Eurofurence, database consistency is
> not checked, so there is probably a crash while writing making it
> inconsistent.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/eurofurence/ef-app_android/issues/21#issuecomment-212912854
> >
>
-- 
DevOps Engineer @ Manus-VR
Commissaris ICT @ Knights of the Kitchen Table
Board Member @ Fontys Hogeschool ICT
