### ISSUE TITLE
Schedule should show events marked as Favorite

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#230]
If an event is marked as favorite,
it should be highlighted in the schedule RecyclerView.
Preferably with the same symbol used in the FloatingActionButton that was used to mark it as a favorite.

**Comment by MarcusWolschon** [comment]
Okay, this seems to happen with a LOT of delay.
It however is not the case right after navigating back from the event-details into the schedule list.

**Comment by Requinard** [comment]
https://www.youtube.com/watch?v=pzz8gkDqZkw&feature=youtu.be

It seems to me it's working as intended, and pretty fast. Are you perhaps running on an older device?

**Comment by MarcusWolschon** [comment]
I can not reproduce this. I noticed for maybe 20 seconds it once and filed my report.
The 8 core flagship phone was otherwise responding normally.

**Comment by Requinard** [comment]
So the issue has gone away on it's own? I just tested it with my phone and it's also working there
