### ISSUE TITLE
Knowledge Base Group view has UI issues

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#234]
Reported by Meo, Android 4.4.4
App Version 2.2.0 (90)

![image](https://user-images.githubusercontent.com/13329381/43716629-1b4dd37e-9985-11e8-98dc-17d004314532.png)

**Comment by Requinard** [comment]
![image](https://user-images.githubusercontent.com/5537850/43773380-d4312a9c-9a45-11e8-8f0b-d6d9bb42486b.png)

cannot reproduce

**Comment by Pinselohrkater** [comment]
@Requinard I was able to reproduce using the emulator on Android 4.4. 

![image](https://user-images.githubusercontent.com/13329381/43781655-b77d422e-9a5d-11e8-929f-fc36f8232483.png)
