### ISSUE TITLE
Edit back-button behaviour

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_android#237]
Either conform to the gplay guidelines and close the app or change it from a dialog to a toast.

Add a setting to manually switch the behaviour

**Comment by Pinselohrkater** [comment]
Please default to "as little user interaction as possible" - if back on home just suspends the app with a toast, that's imho better than a dialog that then completely closes it.

**Comment by MarcusWolschon** [comment]
Indeed, this is very bad behavior.
There are only very few use cases where such a dialog should exist at all.
(e.g. Multiplayer games or video conferences, that can not be paused, where you may loose your progress when accidentally hitting the back button. Even if this does nothing when hitting the home button instead. )
An app is never closed like a desktop application and users DO understand this.
State is persisted and restored as long as there is memory.

**Comment by Requinard** [comment]
Like they say in pirates of the carribean; They're more guidelines than actual rules.

I've added a checkbox for remembering the choice. When that is checked the app will auto-close the next time. This check is not wiped on database resets.
