### ISSUE TITLE
Improper drilldown navigation

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#242]
When in the Event Schedule List and drilling down into a single event,
the NavigationBar does not change.
It should no longer show the NavigationDrawer
(as we are no longer inside a top-level navigation item but have drilled down)
and instead show an UP icon to navigate back up into the Event Schedule List.

Navigation in general:
https://developer.android.com/training/design-navigation/descendant-lateral

Back vs. Up:
https://developer.android.com/training/design-navigation/ancestral-temporal

Up navigation:
https://developer.android.com/training/implementing-navigation/ancestral

**Comment by Requinard** [comment]
This issue is pretty bummer as the current navigation stack does not support any of this behaviour. Will have to hold until next year

**Comment by MarcusWolschon** [comment]
Then let's fix it next year!
But why label it as "wontfix" then?

**Comment by Pinselohrkater** [comment]
Let's do that - sounds reasonable. 👍
