### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by lukashaertel** [eurofurence/ef-app_android#269]
User interface text should be internationalized using strings with platform language conditions. Event description translations are not as feasible.
- [ ] Internationalize UI strings
- [ ] Internationalize dynamic content

**Comment by Nikoshi** [comment]
I'm getting back to android and this looks like a task that I could do^^

**Comment by Nikoshi** [comment]
I'll do it later when I'm at home^^

**Comment by Nikoshi** [comment]
Talked with @Requinard I'm working on it

**Comment by Nikoshi** [comment]
Hey :)
The fixes are available in PR #284
