### ISSUE TITLE
Not remembering login

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#272]
It seems that the app is 
a) not staying logged in (e.g. remembering an OAUTH token)
and
b) not remembering any of the login credentials.
Not only the password but also not remembering reg-nr, and username.
Since they are often stored in the web browser, the user has to look them up and find out what the credentials for the current year as opposed to past decades are.

**Comment by Requinard** [comment]
e7c05a50f87f60a73ea8c5f218584583ee73a35b

Is this behaviour still valid? Tokens will still get cleared when they are no longer valid. This is included in the key itself (which is JWT)

**Comment by MarcusWolschon** [comment]
How long is such a token valid?

**Comment by Pinselohrkater** [comment]
30 days after issuing (=login)

**Comment by MarcusWolschon** [comment]
In such a case a message to the user after a token has expired would be nice.
I'll see at the next update if I'm still logged in.
