### ISSUE TITLE
access to old announcements

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#273]
There does not seem to be a way to navigate to any but the latest 3 announcements.
I remember to specifically not click on one announcement to take care of it later.
But since then there are 3 new ones and I can not figure out what it was about anymore.
The text of the notification got replaced.
Even to the point that I have a screenshot with 2 notifications of this app
at the same time with the same text.

**Comment by MarcusWolschon** [comment]
(I found out what it was. The Glympse tag that I wanted to keep open until I needed the details from that announcement on the arrival day.)

**Comment by Requinard** [comment]
There's a setting to access old announcements in the settings. Since the announcements themselves expire, it is considered non-standard behaviour and thus won't be enabled by default.

**Comment by MarcusWolschon** [comment]
found it "show irrelevant announcements"
