### ISSUE TITLE
Conditional error on event fav

### ISSUE THREAD

**Issue by Nesias** [eurofurence/ef-app_android#279]
Bug: 
Message "This event has already occured!" displayed if you try to fav an event and the time till start is less than than the alert time.

How to reproduce:
- Go to EF App settings, change alert time to something like 120 mins
- Switch over to Event list and select an event with less than 120 mins (or time set in settings)
- try to fav that event -> will result in message written above

(Confirmed in 2 different Android devices)

Expected Result:
Notice that no alert will pop up + event added to list.

- Nesias von Wolfen (ef24: 1489)

**Comment by Fenrikur** [comment]
The issue occurs when the user tries to add an event to their favourites and the difference between the start time of the event and the current time is smaller than the number of minutes set for favourite alerts.
This not only presents the user with the message mentioned above, but also prevents the event from being added to their favourites. It will most likely also prevent users from adding past or currently running events to their favourites as well, which may be considered unwanted behaviour.
