### ISSUE TITLE
useless map

### ISSUE THREAD

**Issue by MarcusWolschon** [eurofurence/ef-app_android#280]
the map displayed in the events is useless.
it's too small to get any idea where this is fragment fits in.
touching it does not navigate to the large map.
it is does not show that a room is not on the the ground floor.
it does not not show your own position.

Sadly I can't upload a screenshot here.

**Comment by Fenrikur** [comment]
The zoom level on the map fragments has since been modified such that the surrounding area of a location is visible as well.
