### ISSUE TITLE
Event Feedback Dialog

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#289]
On event detail, when `IsAcceptingFeedback` on the event record is set to `true`, allow the user to navigate to an *Event Feedback* modal form.

The *Event Feedback* modal form should present the most important event details (Title, Date, From-To, Location, Hosts) and the following input controls:

- A star rating control that allows the user to rate the event between 1 and 5.
- A multi-line message box that allows the user to enter any free text.
- A submit button.

When the user submits the form, post the result to the API Endpoint (see: https://app.eurofurence.org/EF25/swagger/ui/index.html#/EventFeedback/ApiEventFeedbackPost).

- Please block the UI and/or show a loading indicator to ensure multple submissions are not possible.

Android Mockups:
https://www.figma.com/file/K2hXoS5M3Cj6Uue6WXB1Rr/Event-Feedback?node-id=0%3A1

**Comment by Requinard** [comment]
done
