### ISSUE TITLE
Menu: "Collect'em All" Token Pass-Through & Tab Re-Use

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#290]
When clicking on Collect'em All in the menu, ensure that:

- [x] 1. Authentication is passed through:

**URL to open:**
`https://app.eurofurence.org/{$CID}/companion/#/login?embedded=true&returnPath=/collect&token={$AUTH_TOKEN}`

**Example:** (Not working due to sample token.)
https://app.eurofurence.org/EF25/companion/#/login?embedded=true&returnPath=/collect&token=eyJhUGX0dC0Fxxxxxx

- [x] 2. Pass in **[EXTRA_APPLICATION_ID](https://stackoverflow.com/a/13023978)** with the value of **CID** to the intent to ensure that we're not constantly creating new tabs but re-use existing ones.

**Comment by Requinard** [comment]
916a27d222cf9159cd4e37061a10d93f62879e44
