### ISSUE TITLE
Menu: New Item, "Additional Services"

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#291]
- [x] 1. Add a new menu item at the end of the "Personal" group (below Collect'Em All), called "**Additional Services**". Icon to use: https://fontawesome.com/icons/book?style=solid

![image](https://user-images.githubusercontent.com/13329381/58868815-6270a080-86bd-11e9-9098-087d92fb9859.png)

- [x] 2. Clicking on it should open a web-browser with authentication through:

**URL to open:**
`https://app.eurofurence.org/{$CID}/companion/#/login?embedded=true&returnPath=/&token={$AUTH_TOKEN}`

**Example:** (Not working due to sample token.)
https://app.eurofurence.org/EF25/companion/#/login?embedded=true&returnPath=/&token=eyJhUGX0dC0Fxxxxxx

- [x] 3. Pass in **[EXTRA_APPLICATION_ID](https://stackoverflow.com/a/13023978)** with the value of **CID** to the intent to ensure that we're not constantly creating new tabs but re-use existing ones.

**Comment by Requinard** [comment]
f04a7bae59829b0a9cffa75f964d0fa11a99ad9d
