### ISSUE TITLE
Coloured icons

### ISSUE THREAD

**Issue by ralesk** [eurofurence/ef-app_android#317]
I know the current design fad is to have everything the same grey everywhere, but a red heart, a yellow star, a... whatever other markers you have on event lists, those stand out way more than the same colour for every icon.

Yellow and purple would be good for showing which ones are sponsor/supersponsor, in particular.

**Comment by Requinard** [comment]
Thanks, I can't believe I've never thought of this!

**Comment by Requinard** [comment]
![afbeelding](https://user-images.githubusercontent.com/5537850/63377560-a9069a80-c390-11e9-92d1-821d60889e17.png)

**Comment by ralesk** [comment]
That yellow is pretty hard to see, but this does feel like a good step otherwise :D
