### ISSUE TITLE
Stop Browsing

### ISSUE THREAD

**Issue by Rain336** [eurofurence/ef-app_android#325]
The Collect 'em All game as well as the Additional Services are available as a website. This is not very intuitive since the app doesn't even use a `WebView`. Because of that you need to close the Browser and use the app switcher to change back to the app. In an ideal solution this should be implemented in the app and not as a separate website.

**Comment by Requinard** [comment]
this is very much a personal preference issue. For now it has been chosen to open the Collect 'em All in a browser as it feels like a different app.

In any case, a single back button press should lead you right back to the app.
