### ISSUE TITLE
Project can not build out-of-the-box.

### ISSUE THREAD

**Issue by theysconator** [eurofurence/ef-app_android#63]
In the master branch:

In

https://github.com/eurofurence/ef-app_android/blob/master/app/src/main/kotlin/org/eurofurence/connavigator/ui/FragmentViewHome.kt#L20

should the '.layouts.' part in the import be reworded to '.views.' (Or the 'views' folder should be called 'layouts'.)

Also, in

https://github.com/eurofurence/ef-app_android/blob/master/app/src/main/kotlin/org/eurofurence/connavigator/app/ConnavigatorApplication.kt#L35

should the '.subscribeToTest()' part be reworded to '.subscribe()'. (Or the method should be renamed to 'subscribeToTest', of course.)

These two changes allowed me to compile.

**Comment by Requinard** [comment]
Hi,

These errors are regrettably my fault. These changes were moved to a different changelist, and have now been pushed.
