### ISSUE TITLE
Show favourited events in scheduled order

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_android#8]

**Comment by lukashaertel** [comment]
[From discussion on telegram] Concerning this and #5, we might want to use a calendar http://developer.android.com/intl/es/guide/topics/providers/calendar-provider.html which provides reminders and events

**Comment by Requinard** [comment]
Will need the backend version to be completed first

**Comment by Requinard** [comment]
94113f8fed96de5ed6bb123e51c1989ea9125780

Might need some extra ordering

**Comment by Requinard** [comment]
7825f83ad996f5c657d3767de066c1c27b9ea672
