### ISSUE TITLE
Events are displayed White on White

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#95]
Reported by https://t.me/Meokater
Still present in 2.0.1 Build 65

Events are displayed white on white, but are clickable.

![photo_2017-07-04_16-15-12](https://user-images.githubusercontent.com/13329381/27833671-11a0cb0a-60d4-11e7-8333-a0e9cfc8b55e.jpg)

![photo_2017-07-04_16-15-20](https://user-images.githubusercontent.com/13329381/27833670-118bb396-60d4-11e7-92a9-b627a25cb68b.jpg)

**Comment by Requinard** [comment]
Version numbers too please

**Comment by meokater** [comment]
![photo_2017-06-28_22-24-54](https://user-images.githubusercontent.com/29896212/27836148-7e08318e-60de-11e7-93ab-4d69ccaead45.jpg)

please be aware that this Tablet is not rooted, therefore I can not supply any logs.

**Comment by Requinard** [comment]
Times from favorites is known, and has been fixed in 1ee295adff9b669783967a87c3a49a59904034dc

An all white event page however is not reproducible. Please re-open when it becomes reproducible

**Comment by mowny** [comment]
It is here. But now I noticed that favorited events _are_ visible, see for yourself:
![screenshot_2017-07-05-20-00-52](https://user-images.githubusercontent.com/25304296/27878042-2f982132-61bd-11e7-8ecc-de32ef6a2bb4.png)

**Comment by mlehmk** [comment]
created https://github.com/mlehmk/ef-app_android/tree/fix/95
which fixes that issue on Android 5.0 that seems to use a dark theme as base
