### ISSUE TITLE
Login info on home screen not updated after leaving login screen

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#96]
2.0.1 Build 65 on Android 7.1.1 (Emulator)

When logged on, the home screen shows "Hello luchs (...)" on top. 
Open Menu, "Login", "Logout" returns to the home screen with a "Logging you  out, Goodbye!" message, yet the "Hello luchs (...)" item is still present on the top.

Same goes for logging in: After a successful login, the app returns to the home screen, but the "Hello luchs (...)"  message is missing until the next reload of that screen.

Home screen should probably reload when returning from the login screen (or login state changes).

**Comment by Requinard** [comment]
996d80e746bb747e77d5c671500024a3b704ceb8
