### ISSUE TITLE
App crashes when viewing a Knowledge entry detail

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_android#97]
2.0.1 Build 65 on Android 7.1.1 (Emulator)

Tapping on any item causes the app to crash.

![android](https://user-images.githubusercontent.com/13329381/27854343-c2fe5146-6166-11e7-8468-f19e75d435cb.png)

**Comment by Requinard** [comment]
Came from an upgrade to the photoview library where some XML became invalid (something the compiler can't catch)

Fixed in 04e67f01e7a85ac0ca25fd2a8a745c7928e1c1ff
